apiVersion: v1
kind: PersistentVolume
metadata:
  name: cfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  mountOptions:
  - vers=4
  nfs:
    server: 172.16.0.41
    path: "/"
