apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: etcd
  name: etcd-k8s
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    port: port
    scheme: https
    insecureSkipVerify: true
    tlsConfig:
      caFile: /etc/prometheus/secrets/etcd-certs/ca.pem
      certFile: /etc/prometheus/secrets/etcd-certs/node-{{ .Values.masterAname }}.pem
      keyFile: /etc/prometheus/secrets/etcd-certs/node-{{ .Values.masterAname }}-key.pem
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: etcd
