apiVersion: v1
type: kubernetes.io/tls
kind: Secret
metadata:
  name: {{ .Values.dex.secret.name }}
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: {{ .Values.dex.secret.tls.crt | b64enc }}
  tls.key: {{ .Values.dex.secret.tls.key | b64enc }}
