apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  namespace: monitoring
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccount: nginx
      volumes:
        - name: html
          emptyDir: {}
        - name: log
          emptyDir: {}
        - name: conf
          configMap:
            name: nginx-ldap-auth
      containers:
        - image: {{ .Values.imageRepo }}/library/nginx:1.15
          imagePullPolicy: Always
          name: nginx
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: html
            - mountPath: /var/log/nginx
              name: log
            - mountPath: /etc/nginx/conf.d/
              name: conf
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
