apiVersion: v1
kind: Service
metadata:
  name: nginx-ldap-auth-daemon
  namespace: monitoring
  labels:
    app: nginx-ldap-auth-daemon
spec:
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  selector:
    app: nginx-ldap-auth-daemon
  type: ClusterIP
