apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx-ldap-auth-daemon
  namespace: monitoring
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-ldap-auth-daemon
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-ldap-auth-daemon
    spec:
      containers:
        - image: {{ .Values.imageRepo }}/library/nginx-ldap-auth-daemon:latest
          imagePullPolicy: IfNotPresent
          name: nginx-ldap-auth-daemon
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 30Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
