apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: monitoring
spec:
  rules:
  - host: monitoring.{{ .Values.clusterName }}.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 8081
