# Default values for keepalived-vip.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: {{ imageRepo }}/library/keepalived-vip
  tag: v0.2
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector:
  node-role.kubernetes.io/master: ""

tolerations:
 - key: "key"
   operator: "Exists"
   effect: "NoSchedule"

daemonset:
  env:
    interface: "{{ vip_interface }}"
    virtual_router_id: "{{ virtual_router_id }}"
    vips: "{{ vips }}"
    advert_interval: "2"
    all_node_ips: "{{ all_vip_listeners }}"
